### ISSUE TITLE
How to use openssl-cng-engine to open a secure server openssl s_server?

### ISSUE THREAD

**Issue by mqttBridge** [rticommunity/openssl-cng-engine#43]
Hi
I would like add inthe documentation how to use a server using CNG Store. This would be very useful for newbies who would want to use a openssl server without coding.
1.>Open command in Admin mode
2.>  make sure to set the path of the engine-ncrypt.dll in the path variable
3.> notepad ncrypt.conf
# This is ncrypt.conf
openssl_conf = openssl_init

[openssl_init]
engines = engine_section

[engine_section]
ncrypt = ncrypt_section

[ncrypt_section]
dynamic_path = engine-ncrypt
init = 1
debug_level = 2
default_algorithms = ALL

4.> set OPENSSL_CONF=ncrypt.conf
> to test if engine is loaded or not…
5.> openssl engine dynamic -pre SO_PATH:engine-ncrypt -pre LOAD
C:\WINDOWS\system32>openssl engine dynamic -pre SO_PATH:engine-ncrypt -pre LOAD
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:engine-ncrypt
[Success]: LOAD
Loaded: (engine-ncrypt) CryptoAPI: Next Gen (CNG) NCrypt STORE Engine

6.#How to get certificate thumbprint
> openssl storeutl -engine engine-ncrypt -certs cert:/LocalMachine/test345
C:\WINDOWS\system32>openssl storeutl -engine engine-ncrypt -certs cert:/LocalMachine/test345
engine "engine-ncrypt" set.
0: Name: cert:/LocalMachine/test345/6a167fb45ffb4da9f723baf038ccd06a071edb1c
C=IN, S=KAR, L=BAN, O=ABC, OU=bility, CN=aazing.example.com, E=agha@abc.com
Total found: 1

#How to get public certificate from cert uri
C:\Users\INRAK103\Downloads>openssl storeutl -engine engine-ncrypt  -certs cert:/LocalMachine/test345/6a167fb45ffb4da9f723baf038ccd06a071edb1c  > ncrypt.pem [delete engine “engine-encrypt set, certificate, Total found: 1” 
engine "engine-ncrypt" set.
0: Certificate
-----BEGIN CERTIFICATE-----
MIIDkTCCAnkCFHIJRb0rRA7Q0zGwa9k43BRWt0nOMA0GCSqGSIb3DQEBCwUAMIGD
MQswCQYDVQQGEwJJTjEMMAoGA1UECAwDS0FSMQwwCgYDVQQHDANCQU4xDDAKBgNV
BAoMA0FCQjEQMA4GA1UECwwHYWJpbGl0eTEXMBUGA1UEAwwOY2EuYWJpbGl0eS5j
b20xHzAdBgkqhkiG9w0BCQEWEGNhLnJhZ2hhQGFiYi5jb20wHhcNMjEwNDA2MTMw
ODQ1WhcNMjYwNDA1MTMwODQ1WjCBhTELMAkGA1UEBhMCSU4xDDAKBgNVBAgMA0tB
UjEMMAoGA1UEBwwDQkFOMQwwCgYDVQQKDANBQkIxEDAOBgNVBAsMB2FiaWxpdHkx
HDAaBgNVBAMME2thYXppbmcuZXhhbXBsZS5jb20xHDAaBgkqhkiG9w0BCQEWDXJh
Z2hhQGFiYi5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDEwVkP
sjdN9NBP/P0CGkvFbaWQbSNH13qecM7m10VhzxQDlLJEfS5y4ZS+SsgutMSX+7Kz
Xqq1HucyTInFn2i9AEJiJnUuCcH0cJNBi5yB9AYYJQeRjOPvI/cptHUFvA6BUdo9
TJuNtyrc/q2qUEFR7sgUgCx6SutZUglq6lYRBXc03INu9DkZ4GAk3QvbDnX1jOP4
MGw2Z18w8NxfVmsbaGVh4ssfgQWtvG3ucxy5tvDVnk0FQwkTdNp1h/EzvFmIA1n2
ZubOQ0n3vKNRoJa60yr+JA8rD2rJ++JJsleqYUsafaVzRgQMAo0VqjZ1Z0Eq18MV
nwlYWPxm/vYzKE2jAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAHIaoFOpFSvFMtzi
hlUVkYainVWtK8AvuHV3VR1Z5KTqbY4WJEa0I8+DRCh3gvPlgkIuaXGTBUvRAic0
1i9FT6h/lIgzWSOF+NZvMLtinQm8ND5dRgrEs0SgF8ytvu1v0QvtP5losljLH3hS
m6E8/tO5BWLWf2pfzG2BC+S5HomNuPlZwbGoYs7h3BiW7g7wL2TiLUUEdhBHDyu
JnpzLr53fsdd77K6QvLh8Vb6cy+qUST+eSRuns8WB/AJAaWRVftBR0LtbCcY8S1
QswoiuNtl8GxOUowMMHFEHBDU8wCauixGBuf8RoFsD2g6+ENWlvtP42ztaFPYkg
I7/MJAs=
-----END CERTIFICATE-----
Total found: 1

#How to get a encrypted key from the store
> openssl storeutl -engine engine-ncrypt  -keys cert:/LocalMachine/test345/6a167fb45ffb4da9f723baf038ccd06a071edb1c

#We cannot provide both key and cert point to the store. Instead export the public certificate to a file and then point key to the cert store. 
>openssl  s_server  -accept 9200 -status -msg  -engine engine-ncrypt   -keyform engine -key cert:/LocalMachine/test345/6a167fb45ffb4da9f723baf038ccd06a071edb1c -cert ncrypt.pem -tlsextdebug
C:\Users\INRAK103\Downloads>openssl  s_server  -accept 9200 -status -msg  -engine engine-ncrypt   -keyform engine -key cert:/LocalMachine/test345/6a167fb45ffb4da9f723baf038ccd06a071edb1c  -cert ncrypt.pem -tlsextdebug
engine "engine-ncrypt" set.
Calling cng_store_load_privkey uri=cert:/LocalMachine/test345/6a167fb45ffb4da9f723baf038ccd06a071edb1c
Using default temp DH parameters
ACCEPT

>openssl s_client  -connect aazing.example.com:9200 -CAfile myCA.pem

Note: In windows hosts file map this host name to loopback ip.

**Comment by mqttBridge** [comment]
This is not a issue but a guide/doc.

**Comment by reiniert** [comment]
@mqttBridge thanks for the feedback, I will include this, or something along these lines, in the documentation.
One remark: this guide initially mentions `engine-bcrypt` and then uses `engine-ncrypt` in the subsequent commands. That seems like an oversight but I just wanted to double check.

**Comment by mqttBridge** [comment]
I have updated bcrypt to ncrypt. Thanks for notification.
